// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: job_service.proto

package job_service

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

func init() { proto.RegisterFile("job_service.proto", fileDescriptor_4d14b17d30cb4d50) }

var fileDescriptor_4d14b17d30cb4d50 = []byte{
	// 291 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x92, 0x4f, 0x4a, 0xc3, 0x40,
	0x14, 0xc6, 0xed, 0xc2, 0x42, 0x9e, 0x4a, 0xed, 0x20, 0x28, 0xa9, 0x66, 0xe9, 0xb2, 0x05, 0x15,
	0x5c, 0xb7, 0x0d, 0x04, 0x47, 0x57, 0x2d, 0x45, 0x70, 0x23, 0x1d, 0xe7, 0xa1, 0x91, 0x31, 0x2f,
	0x66, 0x5e, 0x3d, 0x8b, 0x87, 0xf0, 0x20, 0x2e, 0x3d, 0x82, 0xc4, 0x8b, 0x88, 0x19, 0x5a, 0xd2,
	0xc6, 0x76, 0x93, 0xe5, 0xfc, 0xbe, 0xf9, 0x7e, 0xf3, 0x17, 0xda, 0xcf, 0xa4, 0xee, 0x2d, 0x66,
	0x6f, 0xf1, 0x03, 0x76, 0xd3, 0x8c, 0x98, 0xc4, 0x4e, 0x09, 0xf9, 0xad, 0xbf, 0xc1, 0x0b, 0x69,
	0x34, 0x2e, 0x3d, 0xfb, 0xd8, 0x06, 0x90, 0xa4, 0xc6, 0x2e, 0x17, 0x97, 0xe0, 0x0d, 0x33, 0x9c,
	0x32, 0x4a, 0x52, 0x62, 0xbf, 0x5b, 0xb6, 0x49, 0x52, 0xfe, 0xd1, 0x2a, 0xb9, 0x8d, 0xf9, 0x29,
	0x9a, 0x5c, 0x85, 0xa2, 0x07, 0xde, 0x24, 0xd5, 0x6b, 0x8b, 0x15, 0x22, 0x06, 0xe0, 0x85, 0x68,
	0xd0, 0x15, 0xd6, 0x7a, 0xfd, 0xce, 0x52, 0x32, 0x42, 0x9b, 0x52, 0x62, 0x71, 0xcc, 0x53, 0x9e,
	0x59, 0x71, 0x01, 0xcd, 0x08, 0x79, 0xb3, 0xa0, 0xba, 0x72, 0x08, 0x10, 0x21, 0xf7, 0x8d, 0x91,
	0xa4, 0xec, 0x4a, 0xf3, 0x26, 0xb6, 0x3c, 0xc2, 0xd7, 0x19, 0x5a, 0xf6, 0x8f, 0x2b, 0x89, 0x24,
	0x35, 0xdf, 0x81, 0xb8, 0x86, 0xb6, 0xb3, 0xb8, 0x53, 0xe8, 0x9a, 0xb2, 0xbd, 0x08, 0x79, 0x68,
	0x62, 0x4c, 0xb8, 0x10, 0x9d, 0x2c, 0x4d, 0x5f, 0x04, 0x73, 0x5b, 0xa7, 0x62, 0x2b, 0x75, 0x9d,
	0x4c, 0x92, 0x72, 0xac, 0x9e, 0x2c, 0x84, 0xdd, 0xbe, 0xd6, 0x0b, 0x20, 0x0e, 0xff, 0x77, 0xd9,
	0xcd, 0x0f, 0x15, 0x41, 0xcb, 0x5d, 0x53, 0x4d, 0xd1, 0xe0, 0xf4, 0x33, 0x0f, 0x1a, 0x5f, 0x79,
	0xd0, 0xf8, 0xce, 0x83, 0xc6, 0xfb, 0x4f, 0xb0, 0x75, 0x77, 0xf0, 0x88, 0x49, 0xf1, 0x95, 0x7b,
	0xa5, 0x9a, 0x6a, 0x16, 0xe8, 0xfc, 0x37, 0x00, 0x00, 0xff, 0xff, 0x36, 0xe9, 0xf2, 0xb6, 0x10,
	0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// JobServiceClient is the client API for JobService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type JobServiceClient interface {
	CreateJob(ctx context.Context, in *Job, opts ...grpc.CallOption) (*JobWithGUID, error)
	UpdateJob(ctx context.Context, in *Job, opts ...grpc.CallOption) (*Job, error)
	DeleteJob(ctx context.Context, in *JobWithGUID, opts ...grpc.CallOption) (*ResponseStatus, error)
	GetJob(ctx context.Context, in *JobWithGUID, opts ...grpc.CallOption) (*Job, error)
	GetAllJobs(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListJobResponse, error)
	GetAllDeletedJobs(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListJobResponse, error)
	GetClientJobs(ctx context.Context, in *ClientJobRequest, opts ...grpc.CallOption) (*ListClientJobs, error)
	GetJobClients(ctx context.Context, in *ClientJobRequest, opts ...grpc.CallOption) (*ListClientJobs, error)
	AddClientJob(ctx context.Context, in *ClientJobs, opts ...grpc.CallOption) (*ResponseStatus, error)
	DeleteClientJob(ctx context.Context, in *ClientJobs, opts ...grpc.CallOption) (*ResponseStatus, error)
}

type jobServiceClient struct {
	cc *grpc.ClientConn
}

func NewJobServiceClient(cc *grpc.ClientConn) JobServiceClient {
	return &jobServiceClient{cc}
}

func (c *jobServiceClient) CreateJob(ctx context.Context, in *Job, opts ...grpc.CallOption) (*JobWithGUID, error) {
	out := new(JobWithGUID)
	err := c.cc.Invoke(ctx, "/job_service.JobService/CreateJob", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobServiceClient) UpdateJob(ctx context.Context, in *Job, opts ...grpc.CallOption) (*Job, error) {
	out := new(Job)
	err := c.cc.Invoke(ctx, "/job_service.JobService/UpdateJob", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobServiceClient) DeleteJob(ctx context.Context, in *JobWithGUID, opts ...grpc.CallOption) (*ResponseStatus, error) {
	out := new(ResponseStatus)
	err := c.cc.Invoke(ctx, "/job_service.JobService/DeleteJob", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobServiceClient) GetJob(ctx context.Context, in *JobWithGUID, opts ...grpc.CallOption) (*Job, error) {
	out := new(Job)
	err := c.cc.Invoke(ctx, "/job_service.JobService/GetJob", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobServiceClient) GetAllJobs(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListJobResponse, error) {
	out := new(ListJobResponse)
	err := c.cc.Invoke(ctx, "/job_service.JobService/GetAllJobs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobServiceClient) GetAllDeletedJobs(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListJobResponse, error) {
	out := new(ListJobResponse)
	err := c.cc.Invoke(ctx, "/job_service.JobService/GetAllDeletedJobs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobServiceClient) GetClientJobs(ctx context.Context, in *ClientJobRequest, opts ...grpc.CallOption) (*ListClientJobs, error) {
	out := new(ListClientJobs)
	err := c.cc.Invoke(ctx, "/job_service.JobService/GetClientJobs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobServiceClient) GetJobClients(ctx context.Context, in *ClientJobRequest, opts ...grpc.CallOption) (*ListClientJobs, error) {
	out := new(ListClientJobs)
	err := c.cc.Invoke(ctx, "/job_service.JobService/GetJobClients", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobServiceClient) AddClientJob(ctx context.Context, in *ClientJobs, opts ...grpc.CallOption) (*ResponseStatus, error) {
	out := new(ResponseStatus)
	err := c.cc.Invoke(ctx, "/job_service.JobService/AddClientJob", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobServiceClient) DeleteClientJob(ctx context.Context, in *ClientJobs, opts ...grpc.CallOption) (*ResponseStatus, error) {
	out := new(ResponseStatus)
	err := c.cc.Invoke(ctx, "/job_service.JobService/DeleteClientJob", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// JobServiceServer is the server API for JobService service.
type JobServiceServer interface {
	CreateJob(context.Context, *Job) (*JobWithGUID, error)
	UpdateJob(context.Context, *Job) (*Job, error)
	DeleteJob(context.Context, *JobWithGUID) (*ResponseStatus, error)
	GetJob(context.Context, *JobWithGUID) (*Job, error)
	GetAllJobs(context.Context, *ListRequest) (*ListJobResponse, error)
	GetAllDeletedJobs(context.Context, *ListRequest) (*ListJobResponse, error)
	GetClientJobs(context.Context, *ClientJobRequest) (*ListClientJobs, error)
	GetJobClients(context.Context, *ClientJobRequest) (*ListClientJobs, error)
	AddClientJob(context.Context, *ClientJobs) (*ResponseStatus, error)
	DeleteClientJob(context.Context, *ClientJobs) (*ResponseStatus, error)
}

// UnimplementedJobServiceServer can be embedded to have forward compatible implementations.
type UnimplementedJobServiceServer struct {
}

func (*UnimplementedJobServiceServer) CreateJob(ctx context.Context, req *Job) (*JobWithGUID, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateJob not implemented")
}
func (*UnimplementedJobServiceServer) UpdateJob(ctx context.Context, req *Job) (*Job, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateJob not implemented")
}
func (*UnimplementedJobServiceServer) DeleteJob(ctx context.Context, req *JobWithGUID) (*ResponseStatus, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteJob not implemented")
}
func (*UnimplementedJobServiceServer) GetJob(ctx context.Context, req *JobWithGUID) (*Job, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetJob not implemented")
}
func (*UnimplementedJobServiceServer) GetAllJobs(ctx context.Context, req *ListRequest) (*ListJobResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllJobs not implemented")
}
func (*UnimplementedJobServiceServer) GetAllDeletedJobs(ctx context.Context, req *ListRequest) (*ListJobResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllDeletedJobs not implemented")
}
func (*UnimplementedJobServiceServer) GetClientJobs(ctx context.Context, req *ClientJobRequest) (*ListClientJobs, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetClientJobs not implemented")
}
func (*UnimplementedJobServiceServer) GetJobClients(ctx context.Context, req *ClientJobRequest) (*ListClientJobs, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetJobClients not implemented")
}
func (*UnimplementedJobServiceServer) AddClientJob(ctx context.Context, req *ClientJobs) (*ResponseStatus, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddClientJob not implemented")
}
func (*UnimplementedJobServiceServer) DeleteClientJob(ctx context.Context, req *ClientJobs) (*ResponseStatus, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteClientJob not implemented")
}

func RegisterJobServiceServer(s *grpc.Server, srv JobServiceServer) {
	s.RegisterService(&_JobService_serviceDesc, srv)
}

func _JobService_CreateJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Job)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobServiceServer).CreateJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/job_service.JobService/CreateJob",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobServiceServer).CreateJob(ctx, req.(*Job))
	}
	return interceptor(ctx, in, info, handler)
}

func _JobService_UpdateJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Job)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobServiceServer).UpdateJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/job_service.JobService/UpdateJob",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobServiceServer).UpdateJob(ctx, req.(*Job))
	}
	return interceptor(ctx, in, info, handler)
}

func _JobService_DeleteJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JobWithGUID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobServiceServer).DeleteJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/job_service.JobService/DeleteJob",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobServiceServer).DeleteJob(ctx, req.(*JobWithGUID))
	}
	return interceptor(ctx, in, info, handler)
}

func _JobService_GetJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JobWithGUID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobServiceServer).GetJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/job_service.JobService/GetJob",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobServiceServer).GetJob(ctx, req.(*JobWithGUID))
	}
	return interceptor(ctx, in, info, handler)
}

func _JobService_GetAllJobs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobServiceServer).GetAllJobs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/job_service.JobService/GetAllJobs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobServiceServer).GetAllJobs(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JobService_GetAllDeletedJobs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobServiceServer).GetAllDeletedJobs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/job_service.JobService/GetAllDeletedJobs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobServiceServer).GetAllDeletedJobs(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JobService_GetClientJobs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClientJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobServiceServer).GetClientJobs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/job_service.JobService/GetClientJobs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobServiceServer).GetClientJobs(ctx, req.(*ClientJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JobService_GetJobClients_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClientJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobServiceServer).GetJobClients(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/job_service.JobService/GetJobClients",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobServiceServer).GetJobClients(ctx, req.(*ClientJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JobService_AddClientJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClientJobs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobServiceServer).AddClientJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/job_service.JobService/AddClientJob",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobServiceServer).AddClientJob(ctx, req.(*ClientJobs))
	}
	return interceptor(ctx, in, info, handler)
}

func _JobService_DeleteClientJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClientJobs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobServiceServer).DeleteClientJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/job_service.JobService/DeleteClientJob",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobServiceServer).DeleteClientJob(ctx, req.(*ClientJobs))
	}
	return interceptor(ctx, in, info, handler)
}

var _JobService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "job_service.JobService",
	HandlerType: (*JobServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateJob",
			Handler:    _JobService_CreateJob_Handler,
		},
		{
			MethodName: "UpdateJob",
			Handler:    _JobService_UpdateJob_Handler,
		},
		{
			MethodName: "DeleteJob",
			Handler:    _JobService_DeleteJob_Handler,
		},
		{
			MethodName: "GetJob",
			Handler:    _JobService_GetJob_Handler,
		},
		{
			MethodName: "GetAllJobs",
			Handler:    _JobService_GetAllJobs_Handler,
		},
		{
			MethodName: "GetAllDeletedJobs",
			Handler:    _JobService_GetAllDeletedJobs_Handler,
		},
		{
			MethodName: "GetClientJobs",
			Handler:    _JobService_GetClientJobs_Handler,
		},
		{
			MethodName: "GetJobClients",
			Handler:    _JobService_GetJobClients_Handler,
		},
		{
			MethodName: "AddClientJob",
			Handler:    _JobService_AddClientJob_Handler,
		},
		{
			MethodName: "DeleteClientJob",
			Handler:    _JobService_DeleteClientJob_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "job_service.proto",
}
