// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: client_service.proto

package client_service

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

func init() { proto.RegisterFile("client_service.proto", fileDescriptor_eee24fc862d835ee) }

var fileDescriptor_eee24fc862d835ee = []byte{
	// 323 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x93, 0xc1, 0x4a, 0xf3, 0x40,
	0x10, 0xc7, 0xbf, 0x5e, 0x0a, 0xdf, 0xd8, 0xf6, 0x30, 0x16, 0x95, 0x08, 0x39, 0x88, 0x1e, 0xbc,
	0x54, 0xd0, 0xbb, 0xa0, 0xa9, 0xc6, 0x82, 0x60, 0x49, 0x8d, 0x01, 0x2f, 0x12, 0xbb, 0xa3, 0x5d,
	0xd8, 0x26, 0x69, 0x76, 0xa3, 0xaf, 0xe2, 0x23, 0xf8, 0x28, 0x1e, 0x7d, 0x04, 0x89, 0x2f, 0x22,
	0x64, 0x5b, 0x31, 0x6b, 0x4a, 0x3c, 0xf4, 0x98, 0xff, 0x7f, 0x7e, 0xbf, 0x19, 0x48, 0x02, 0xdd,
	0xb1, 0xe0, 0x14, 0xa9, 0x3b, 0x49, 0xe9, 0x13, 0x1f, 0x53, 0x2f, 0x49, 0x63, 0x15, 0x63, 0xa7,
	0x9c, 0x5a, 0x38, 0x7f, 0x9e, 0xc6, 0x8c, 0x84, 0x9e, 0x39, 0x7c, 0x6d, 0x42, 0xdb, 0x29, 0xe2,
	0x91, 0x9e, 0xc2, 0x73, 0x68, 0x39, 0x29, 0x85, 0x8a, 0x74, 0x8c, 0x1b, 0x3d, 0x43, 0xae, 0x73,
	0xcb, 0xae, 0xce, 0x03, 0xae, 0x26, 0xae, 0x3f, 0xe8, 0xa3, 0x03, 0xff, 0x5d, 0x52, 0x73, 0x49,
	0xcd, 0xb0, 0xb5, 0x64, 0x09, 0x1e, 0x43, 0xcb, 0x4f, 0x58, 0xfd, 0x31, 0xcb, 0xf8, 0x6b, 0x68,
	0xf5, 0x49, 0xd0, 0x37, 0x5f, 0x77, 0xc7, 0xae, 0xd9, 0xff, 0xa4, 0x3d, 0x92, 0x49, 0x1c, 0x49,
	0xc2, 0x21, 0xb4, 0x5d, 0x52, 0x27, 0x42, 0xe8, 0x5c, 0xe2, 0xb6, 0x89, 0x5d, 0x72, 0xa9, 0x3c,
	0x9a, 0x65, 0x24, 0x95, 0xb5, 0x53, 0x55, 0x1a, 0xc6, 0x00, 0xba, 0xda, 0xa8, 0xf7, 0xb1, 0x95,
	0x89, 0x6f, 0x60, 0x5d, 0x8b, 0x2f, 0x38, 0x63, 0x14, 0xad, 0xcc, 0xeb, 0xc2, 0x9a, 0x1f, 0xf1,
	0x59, 0x46, 0x67, 0xd3, 0x90, 0x0b, 0xdc, 0x32, 0x91, 0x81, 0xd4, 0xf5, 0xef, 0xcf, 0x64, 0xa1,
	0x18, 0xa9, 0x50, 0x65, 0x12, 0xaf, 0xa0, 0xad, 0xdf, 0xb0, 0x47, 0x0f, 0x29, 0xc9, 0x09, 0x56,
	0x00, 0x45, 0xb1, 0xb8, 0xae, 0x4e, 0x18, 0x40, 0x47, 0x0b, 0x87, 0xa1, 0x94, 0xcf, 0x71, 0xca,
	0x70, 0xcf, 0x24, 0xca, 0xfd, 0x1f, 0xc5, 0xa7, 0xfb, 0x6f, 0xb9, 0xdd, 0x78, 0xcf, 0xed, 0xc6,
	0x47, 0x6e, 0x37, 0x5e, 0x3e, 0xed, 0x7f, 0xb7, 0x9b, 0x8f, 0x14, 0x15, 0xbf, 0xd1, 0x41, 0x99,
	0xbc, 0x6f, 0x16, 0xe9, 0xd1, 0x57, 0x00, 0x00, 0x00, 0xff, 0xff, 0xc0, 0x4a, 0x9f, 0x8f, 0x98,
	0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ClientServiceClient is the client API for ClientService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ClientServiceClient interface {
	CreateClient(ctx context.Context, in *Client, opts ...grpc.CallOption) (*ClientWithGUID, error)
	GetClient(ctx context.Context, in *ClientWithGUID, opts ...grpc.CallOption) (*Client, error)
	UpdateClient(ctx context.Context, in *Client, opts ...grpc.CallOption) (*Client, error)
	DeleteClient(ctx context.Context, in *ClientWithGUID, opts ...grpc.CallOption) (*DeleteClientResponse, error)
	GetAllClients(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListClientResponse, error)
	GetAllDeletedClients(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListClientResponse, error)
	GetAllHiddenClients(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListClientResponse, error)
	UniqueEmail(ctx context.Context, in *IsUnique, opts ...grpc.CallOption) (*ResponseStatus, error)
	UpdateRefresh(ctx context.Context, in *RefreshRequest, opts ...grpc.CallOption) (*ResponseStatus, error)
	UpdatePassword(ctx context.Context, in *UpdatePasswordRequest, opts ...grpc.CallOption) (*ResponseStatus, error)
}

type clientServiceClient struct {
	cc *grpc.ClientConn
}

func NewClientServiceClient(cc *grpc.ClientConn) ClientServiceClient {
	return &clientServiceClient{cc}
}

func (c *clientServiceClient) CreateClient(ctx context.Context, in *Client, opts ...grpc.CallOption) (*ClientWithGUID, error) {
	out := new(ClientWithGUID)
	err := c.cc.Invoke(ctx, "/client_service.ClientService/CreateClient", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientServiceClient) GetClient(ctx context.Context, in *ClientWithGUID, opts ...grpc.CallOption) (*Client, error) {
	out := new(Client)
	err := c.cc.Invoke(ctx, "/client_service.ClientService/GetClient", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientServiceClient) UpdateClient(ctx context.Context, in *Client, opts ...grpc.CallOption) (*Client, error) {
	out := new(Client)
	err := c.cc.Invoke(ctx, "/client_service.ClientService/UpdateClient", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientServiceClient) DeleteClient(ctx context.Context, in *ClientWithGUID, opts ...grpc.CallOption) (*DeleteClientResponse, error) {
	out := new(DeleteClientResponse)
	err := c.cc.Invoke(ctx, "/client_service.ClientService/DeleteClient", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientServiceClient) GetAllClients(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListClientResponse, error) {
	out := new(ListClientResponse)
	err := c.cc.Invoke(ctx, "/client_service.ClientService/GetAllClients", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientServiceClient) GetAllDeletedClients(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListClientResponse, error) {
	out := new(ListClientResponse)
	err := c.cc.Invoke(ctx, "/client_service.ClientService/GetAllDeletedClients", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientServiceClient) GetAllHiddenClients(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListClientResponse, error) {
	out := new(ListClientResponse)
	err := c.cc.Invoke(ctx, "/client_service.ClientService/GetAllHiddenClients", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientServiceClient) UniqueEmail(ctx context.Context, in *IsUnique, opts ...grpc.CallOption) (*ResponseStatus, error) {
	out := new(ResponseStatus)
	err := c.cc.Invoke(ctx, "/client_service.ClientService/UniqueEmail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientServiceClient) UpdateRefresh(ctx context.Context, in *RefreshRequest, opts ...grpc.CallOption) (*ResponseStatus, error) {
	out := new(ResponseStatus)
	err := c.cc.Invoke(ctx, "/client_service.ClientService/UpdateRefresh", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientServiceClient) UpdatePassword(ctx context.Context, in *UpdatePasswordRequest, opts ...grpc.CallOption) (*ResponseStatus, error) {
	out := new(ResponseStatus)
	err := c.cc.Invoke(ctx, "/client_service.ClientService/UpdatePassword", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ClientServiceServer is the server API for ClientService service.
type ClientServiceServer interface {
	CreateClient(context.Context, *Client) (*ClientWithGUID, error)
	GetClient(context.Context, *ClientWithGUID) (*Client, error)
	UpdateClient(context.Context, *Client) (*Client, error)
	DeleteClient(context.Context, *ClientWithGUID) (*DeleteClientResponse, error)
	GetAllClients(context.Context, *ListRequest) (*ListClientResponse, error)
	GetAllDeletedClients(context.Context, *ListRequest) (*ListClientResponse, error)
	GetAllHiddenClients(context.Context, *ListRequest) (*ListClientResponse, error)
	UniqueEmail(context.Context, *IsUnique) (*ResponseStatus, error)
	UpdateRefresh(context.Context, *RefreshRequest) (*ResponseStatus, error)
	UpdatePassword(context.Context, *UpdatePasswordRequest) (*ResponseStatus, error)
}

// UnimplementedClientServiceServer can be embedded to have forward compatible implementations.
type UnimplementedClientServiceServer struct {
}

func (*UnimplementedClientServiceServer) CreateClient(ctx context.Context, req *Client) (*ClientWithGUID, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateClient not implemented")
}
func (*UnimplementedClientServiceServer) GetClient(ctx context.Context, req *ClientWithGUID) (*Client, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetClient not implemented")
}
func (*UnimplementedClientServiceServer) UpdateClient(ctx context.Context, req *Client) (*Client, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateClient not implemented")
}
func (*UnimplementedClientServiceServer) DeleteClient(ctx context.Context, req *ClientWithGUID) (*DeleteClientResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteClient not implemented")
}
func (*UnimplementedClientServiceServer) GetAllClients(ctx context.Context, req *ListRequest) (*ListClientResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllClients not implemented")
}
func (*UnimplementedClientServiceServer) GetAllDeletedClients(ctx context.Context, req *ListRequest) (*ListClientResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllDeletedClients not implemented")
}
func (*UnimplementedClientServiceServer) GetAllHiddenClients(ctx context.Context, req *ListRequest) (*ListClientResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllHiddenClients not implemented")
}
func (*UnimplementedClientServiceServer) UniqueEmail(ctx context.Context, req *IsUnique) (*ResponseStatus, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UniqueEmail not implemented")
}
func (*UnimplementedClientServiceServer) UpdateRefresh(ctx context.Context, req *RefreshRequest) (*ResponseStatus, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateRefresh not implemented")
}
func (*UnimplementedClientServiceServer) UpdatePassword(ctx context.Context, req *UpdatePasswordRequest) (*ResponseStatus, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdatePassword not implemented")
}

func RegisterClientServiceServer(s *grpc.Server, srv ClientServiceServer) {
	s.RegisterService(&_ClientService_serviceDesc, srv)
}

func _ClientService_CreateClient_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Client)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientServiceServer).CreateClient(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/client_service.ClientService/CreateClient",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientServiceServer).CreateClient(ctx, req.(*Client))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClientService_GetClient_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClientWithGUID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientServiceServer).GetClient(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/client_service.ClientService/GetClient",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientServiceServer).GetClient(ctx, req.(*ClientWithGUID))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClientService_UpdateClient_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Client)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientServiceServer).UpdateClient(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/client_service.ClientService/UpdateClient",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientServiceServer).UpdateClient(ctx, req.(*Client))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClientService_DeleteClient_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClientWithGUID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientServiceServer).DeleteClient(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/client_service.ClientService/DeleteClient",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientServiceServer).DeleteClient(ctx, req.(*ClientWithGUID))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClientService_GetAllClients_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientServiceServer).GetAllClients(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/client_service.ClientService/GetAllClients",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientServiceServer).GetAllClients(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClientService_GetAllDeletedClients_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientServiceServer).GetAllDeletedClients(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/client_service.ClientService/GetAllDeletedClients",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientServiceServer).GetAllDeletedClients(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClientService_GetAllHiddenClients_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientServiceServer).GetAllHiddenClients(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/client_service.ClientService/GetAllHiddenClients",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientServiceServer).GetAllHiddenClients(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClientService_UniqueEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsUnique)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientServiceServer).UniqueEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/client_service.ClientService/UniqueEmail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientServiceServer).UniqueEmail(ctx, req.(*IsUnique))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClientService_UpdateRefresh_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefreshRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientServiceServer).UpdateRefresh(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/client_service.ClientService/UpdateRefresh",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientServiceServer).UpdateRefresh(ctx, req.(*RefreshRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClientService_UpdatePassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientServiceServer).UpdatePassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/client_service.ClientService/UpdatePassword",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientServiceServer).UpdatePassword(ctx, req.(*UpdatePasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ClientService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "client_service.ClientService",
	HandlerType: (*ClientServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateClient",
			Handler:    _ClientService_CreateClient_Handler,
		},
		{
			MethodName: "GetClient",
			Handler:    _ClientService_GetClient_Handler,
		},
		{
			MethodName: "UpdateClient",
			Handler:    _ClientService_UpdateClient_Handler,
		},
		{
			MethodName: "DeleteClient",
			Handler:    _ClientService_DeleteClient_Handler,
		},
		{
			MethodName: "GetAllClients",
			Handler:    _ClientService_GetAllClients_Handler,
		},
		{
			MethodName: "GetAllDeletedClients",
			Handler:    _ClientService_GetAllDeletedClients_Handler,
		},
		{
			MethodName: "GetAllHiddenClients",
			Handler:    _ClientService_GetAllHiddenClients_Handler,
		},
		{
			MethodName: "UniqueEmail",
			Handler:    _ClientService_UniqueEmail_Handler,
		},
		{
			MethodName: "UpdateRefresh",
			Handler:    _ClientService_UpdateRefresh_Handler,
		},
		{
			MethodName: "UpdatePassword",
			Handler:    _ClientService_UpdatePassword_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "client_service.proto",
}
